# Package Build Configuration 
name: PCK.AUTOMIC_ORACLE_OSB

source: ae
  
# binary object resource mapping will be defined here
binaries:
  
  - object: RESOURCES/LIBS/PCK.AUTOMIC_ORACLE_OSB.PRV.STORE
    resources: 
      - name: CREATE_SESSION
        type: TEXT
        path: tools/osbtool/resources/pythonscripts/pck_osb_create_session.py
        version: 1.0.0